[build]
builder = "nixpacks"

[build.nixpacksPlan.phases.setup]
nixPkgs = ["nodejs_20", "python311"]

[build.nixpacksPlan.phases.install]
cmds = ["./build.sh"]

[deploy]
startCommand = ".venv/bin/uvicorn backend.main:app --host 0.0.0.0 --port $PORT"
